### ISSUE TITLE
First question remark incorrectly mentions 68,000 instead of 68,000,000

### ISSUE THREAD

**Issue by jorisroovers** [kamalmarhubi/one-second#13]
After completing the first question, a remark appears, stating

> Now that you've guessed
> 
> When I see code like this, I think about how much time a millisecond is -- it's imperceptible to me, but apparently you can run 68,000 iterations of an empty loop in a millisecond, even in Python!

 This remark mentions 68,000 iterations while the correct answer is 68,000,000 iterations.

**Comment by shastah** [comment]
There's no typo, you've misread the remark. It's about how much time one *milisecond* is, not one second.
